// <auto-generated/>
#pragma warning disable
#nullable enable

namespace Test
{
    [System.Serializable]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("ExceptionClassGenerator", "1.0.0.0")]
    public partial class TestClassScoped : System.Exception
    {
        /// <summary>
        /// Creates an instance of the <see cref="TestClassScoped"/> class.
        /// </summary>
        public TestClassScoped()
        {}

        /// <summary>
        /// Creates an instance of the <see cref="TestClassScoped"/> class.
        /// </summary>
        /// <param name="message">Message of the exception</param>
        public TestClassScoped(string message)
            : base(message)
        {}

        /// <summary>
        /// Creates an instance of the <see cref="TestClassScoped"/> class.
        /// </summary>
        /// <param name="message">Message of the exception</param>
        /// <param name="innerException">Optional inner exception</param>
        public TestClassScoped(string message, System.Exception innerException)
            : base(message, innerException)
        {}

        /// <summary>
        /// Initializes a new instance of the <see cref="TestClassScoped"/> class.
        /// </summary>
        /// <param name="info">Serialization info</param>
        /// <param name="context">Serialization context</param>
        protected TestClassScoped(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
            : base(info, context)
        {
        }
    }
}