// <auto-generated/>
#pragma warning disable
#nullable enable

using System.Collections.Generic;

namespace Test
{
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("AlwaysInitializedPropertyGenerator", "1.0.0.0")]
    public partial class TestClass
    {
        public List<int> Field1
        {
            get
            {
                if (_field1 == default)
                {
                    _field1 = new List<int>();
                }

                return _field1;
            }
            set { _field1 = value; }
        }
    }
}