// <auto-generated/>
#pragma warning disable
#nullable enable

using System.Collections.Generic;

namespace Test
{
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("AlwaysInitializedPropertyGenerator", "1.0.0.0")]
    public partial class TestClass
    {
        public List<int> Field1
        {
            get
            {
                if (_field1 == default)
                {
                    _field1 = new List<int>();
                }

                return _field1;
            }
            set { _field1 = value; }
        }


        /// <summary>
        /// Some documentation
        /// </summary>
        public List<int> Field2
        {
            get
            {
                if (_field2 == default)
                {
                    _field2 = new List<int>();
                }

                return _field2;
            }
            set { _field2 = value; }
        }

        public List<int> Field4
        {
            get
            {
                if (_field4 == default)
                {
                    _field4 = new List<int>();
                }

                return _field4;
            }
            set { _field4 = value; }
        }

        public List<int> Field5
        {
            get
            {
                if (_field5 == default)
                {
                    _field5 = new List<int>();
                }

                return _field5;
            }
            set { _field5 = value; }
        }
    }
}