// <auto-generated/>
#pragma warning disable
#nullable enable

using System.Threading.Tasks;

namespace Test
{
    public partial class TestClass
    {
        [System.CodeDom.Compiler.GeneratedCodeAttribute("AsyncToSyncConverterGenerator", "1.0.0.0")]
        public void MainMethod1()
        {
            TheMethod();
        }
    }
}